active=yes
admin=yes
reseller=yes
user=yes
installed=yes
name=Ultimate WordPress Manager
version=1.2.25
author=tuend-work
update_url=https://raw.githubusercontent.com/tuend-work/ultimate-directadmin-wordpress-manager/main/plugin.conf
menu_admin=images/menu_admin.json
menu_reseller=images/menu_reseller.json
menu_user=images/menu_user.json
